// Single source of truth for "what shipped". The public /changelog page renders
// this, and the weekly product-update email is assembled from it — so every claim
// in that email is something that actually went live. Newest release first.

export type Release = { v: string; date: string; items: string[] };

export const RELEASES: Release[] = [
  { v: "6.35.0", date: "Latest", items: ["New ‘The moat’ section on the homepage — spelling out the defensible advantages competitors can’t copy: a memory that compounds per customer, one operating brain (not 130 point tools), a system that acts (not just advises), and deep vertical + AI-search tuning"] },
  { v: "6.34.0", date: "Earlier", items: ["Your workspace now knows its industry — pick from 25 industries in Settings and Cortex tailors itself to you", "The dashboard shows a ‘Built for [your industry]’ playbook that maps your real problems to the exact tools that solve them", "AI Agents open straight to your industry automatically — no more scrolling to find your pack"] },
  { v: "6.33.0", date: "Earlier", items: ["A refreshed, modern look — cleaner light and dark themes, with an easy light/dark switch right in the sidebar", "Reorganised sidebar — every section now collapses into clear headers with counts, so 130+ tools stay tidy and you only see what you need", "The living Workforce map is back — the interactive graph where every AI agent connects to your central brain and lights up as you activate them, now paired with the clean team grid"] },
  { v: "6.32.0", date: "Earlier", items: ["Payments are now Cashfree-only — plan upgrades and credit top-ups go exclusively through Cashfree, with the Razorpay fallback removed from checkout for a single, consistent flow"] },
  { v: "6.31.0", date: "Earlier", items: ["Fairer credits — if an AI run (Deep Dive, Bank or GST read) returns nothing usable, its credits are automatically refunded, so you're never billed for a failed run", "Hardened payments — the Razorpay fallback is now idempotent like Cashfree: a retried or duplicated payment verification can never double-charge or double-grant credits", "Under-the-hood robustness pass across the money + AI paths"] },
  { v: "6.30.0", date: "Earlier", items: ["One-click actions from your plan — a priority like ‘chase overdue invoices’ now opens AI Outreach with the brief already filled, so you draft and send in a couple of clicks", "New Adoption dashboard in Super Admin — new signups this week & month, activated workspaces, paid vs trial, and a recent-signups table at a glance", "The plan is now a true do-it loop: read your numbers → decide → draft the action → send"] },
  { v: "6.29.0", date: "Earlier", items: ["New My Plan page — your AI-chosen priorities become a checklist you can tick off, with a progress bar and one-tap refresh", "Each action opens the exact tool that does it — the plan is fully actionable, not just advice", "Optional weekly ‘plan for the week’ email delivers those same priorities to your inbox every Monday (opt-out anytime)", "Both powered by the same engine that reads your real numbers — so the plan is always about your business"] },
  { v: "6.28.0", date: "Earlier", items: ["Cortex now tells you what to do — a new ‘Do this now’ command layer on your dashboard reads your business and ranks the top 3–5 actions for the week", "Each priority links straight to the exact tool, so 130+ tools become the few that matter — you always know where to start", "New workspaces get a clear ‘get set up in a minute’ path instead of a blank dashboard", "Clearer positioning throughout: MNB Cortex is your AI COO — it watches your numbers and tells you what to do next"] },
  { v: "6.27.0", date: "Earlier", items: ["Security fix — pricing inquiries are now strictly scoped to your own workspace; a customer can never see another's leads", "New signups are reliably set up — your business name is applied, a 3-day trial starts, and starter credits are granted automatically", "The trial paywall now shows the correct live plan prices", "A full app audit confirmed every route and API is healthy (no server errors)"] },
  { v: "6.26.0", date: "Earlier", items: ["A far clearer AI Agents experience — no more zoom-and-hunt on a dense map", "Start with ‘What do you want to do?’ → pick a team (Sales, Marketing, Operations, Finance…) or your industry → see just those agents as clean, animated cards", "The Workforce page is now a tidy team grid that drops you straight into the right agents", "The full run → revise → export flow is unchanged — just easier to get to"] },
  { v: "6.25.0", date: "Earlier", items: ["A polished new in-app look — a calmer, layered canvas replaces the flat background, with deeper, softer cards throughout", "Refined sidebar with a lighter, more premium active state (accent bar instead of a heavy fill) and a glassy surface", "Subtle motion and a cleaner topbar — the inside of the app now matches the landing"] },
  { v: "6.24.0", date: "Earlier", items: ["Real accounts — sign up and sign in with email + password (or Google, or a one-time email link), all on your own domain", "New customers get a fully working workspace and a 3-day trial created automatically on first sign-in — no more empty app", "Polished new sign-in screen with clear ‘Sign in’ / ‘Create account’ tabs"] },
  { v: "6.23.0", date: "Earlier", items: ["Production-ready payments — Cashfree live checkout is now hardened for real money", "Signature-verified webhook so a plan or top-up activates reliably even if the customer closes the tab", "Idempotent activation — a page refresh or a replayed webhook can never grant credits or a plan twice", "Every payment is cross-checked server-side against the catalogue price and bound to the paying workspace", "Security: upgraded the web framework to the latest patched release"] },
  { v: "6.22.0", date: "Earlier", items: ["Industry-tuned everywhere — a new interactive ‘see it for your industry’ picker on the homepage speaks your business, not generic dashboards", "Rebuilt Industries page covering 25+ industries (manufacturing, D2C, services, jewellery, distribution, clinics, restaurants, salons, logistics, real estate & more) — each with its real problems and the exact Cortex tools that solve them", "Every industry maps straight to the tools that fix it, so you see value in seconds"] },
  { v: "6.21.0", date: "Earlier", items: ["New problem-led homepage — names the real SME pains (scattered numbers, late warnings, pricey consultants) and shows how Cortex fixes each", "Full feature showcase — all 130+ tools, 300+ agents and Cortex Memory laid out by the job they do, so you can see the whole platform at a glance", "Fixed: Cortex Deep Dive is now live in production (its page and API were previously unreachable)"] },
  { v: "6.20.0", date: "Earlier", items: ["Deeper Bank Statement Intelligence — now with a cashflow health score, month-by-month trend, recurring-payment detection, top payees/payers and runway signals", "Deeper GST Reader — effective tax rate, ITC utilisation, liability composition and a filing-readiness checklist", "New AI Tools hub — every flagship Cortex capability, organised by the job it does, with what you get and its credit cost", "All figures computed in code from your data, never guessed"] },
  { v: "6.19.0", date: "Earlier", items: ["Weekly product-update email — a short, friendly note each week covering what actually shipped, in plain language", "Sent only to your own account holders, one email per person, with a working one-click unsubscribe", "Built on the real changelog, so it never announces anything that isn't live"] },
  { v: "6.18.0", date: "Earlier", items: ["Smooth first-run onboarding tour — a friendly 6-step welcome that shows you how to add data, ask Cortex, let it act, and get found by AI", "Keyboard-navigable, skippable, and re-openable anytime with ?tour=1"] },
  { v: "6.17.0", date: "Earlier", items: ["Made real — your workspace now shows only your own data, never demo numbers", "Empty workspace? The dashboard shows an honest ‘connect your data’ state with one-tap import, and the AI refuses to invent figures", "Sample data now appears only in the logged-out public preview", "The moment you upload a bank statement / GST return / CSV, the whole app comes alive with your real numbers"] },
  { v: "6.16.0", date: "Earlier", items: ["GST Return Reader — upload a GSTR (CSV/PDF) and get your real turnover, tax split, ITC and net payable, grounded to Memory", "AI Outreach — the act-on-your-behalf loop: Cortex drafts a payment reminder / follow-up / supplier note, you approve, it sends by email or WhatsApp", "Every send is reviewed and approved by you; email goes from your own domain with replies routed to you"] },
  { v: "6.15.0", date: "Earlier", items: ["Bank Statement Intelligence — upload a statement (CSV/PDF) and Cortex reads your real cash truth", "Categorises every transaction, shows where the money went, and computes real money-in / out / net cash flow", "Save it to Cortex Memory and your AI CEO chat, Deep Dive and reports start using your real numbers", "Read in your browser; nothing stored unless you save it"] },
  { v: "6.14.0", date: "Earlier", items: ["New brand identity — “The AI operating brain for your business, and it never forgets.”", "Homepage, metadata and social share image re-skinned around the operating-brain positioning", "Leans on the real moat: one brain across your whole company, grounded in Cortex Memory, that acts"] },
  { v: "6.13.0", date: "Earlier", items: ["AI Visibility (AEO) — see whether ChatGPT, Gemini & Perplexity recommend your business when buyers ask", "Runs your buyer questions through live AI engines, scores your visibility, shows who's recommended instead, and drafts the content that gets you cited", "New free public 'AI Visibility check' lead magnet at /ai-visibility", "In-app tool under Intelligence → AI Visibility; save the fix to Cortex Memory"] },
  { v: "6.12.0", date: "Earlier", items: ["Cortex Deep Dive — a new agentic AI tool that reasons in three passes: diagnose → decide → draft the first action", "20 focus areas — cash, pricing, marketing, inventory, receivables, costs, churn, risk, fundraising, exports & more (or ask any question)", "Each run gives a root-cause analysis, three costed options, a 30-day plan and a ready-to-send draft", "Save any Deep Dive straight to Cortex Memory, download it as Markdown, or copy it", "Grounded in your live data and Cortex Memory; 12 credits per run"] },
  { v: "6.11.0", date: "Earlier", items: ["One-click customer onboarding in Super Admin — create a workspace, set plan + credits, and email an activation link in a single action", "New customers own their workspace automatically when they sign up with the invited email", "Reuses the ledger-aware credit system; no password handling on your side"] },
  { v: "6.10.0", date: "Earlier", items: ["New Compare page — Cortex vs ERP, CRM, ChatGPT & consultants", "New Resources hub with practical SME playbooks (cash runway, DSO, AI-COO) for SEO", "Social-proof band on the homepage — MNB Research, Shark Tank India, DPIIT, AbroBot", "All new pages wired into nav, footer and sitemap"] },
  { v: "6.9.0", date: "Earlier", items: ["Live “Ask Cortex” demo on the homepage — watch the AI answer real business questions", "New free Business Health Check tool — a 60-second score, risk breakdown & fix plan (captures leads)", "New Industries page — tailored value for manufacturing, D2C, services, jewellery, distribution & clinics", "Health-check & industry leads flow into your Leads inbox, tagged by source"] },
  { v: "6.8.0", date: "Earlier", items: ["New dedicated Features page — the full product, laid out beautifully", "In-product preview on the homepage + an FAQ", "Pricing now switches between INR and USD", "Pricing requests email you instantly and land in your Leads inbox — approve & grant credits from Super Admin", "Reply-to goes straight to the prospect"] },
  { v: "6.7.0", date: "Earlier", items: ["All-new editorial website — a bold, agency-grade redesign", "Kinetic headlines, smooth scroll, custom cursor & big hover-reveal capability list", "Redesigned landing, pricing and all legal/contact pages with a shared header & footer", "Respects reduced-motion; fully responsive with a full-screen mobile menu"] },
  { v: "6.6.0", date: "Earlier", items: ["Legal pages live — Terms & Conditions, Privacy Policy, Refund & Cancellation Policy, and Contact", "Required for Cashfree activation; linked from the landing and pricing footers", "Pricing page now shows the secure-payments + policy notice at checkout"] },
  { v: "6.5.0", date: "Earlier", items: ["Cashfree Payments — accept live payments for plans and credit top-ups", "6 pricing tiers with real monthly & annual prices (Solo ₹799 → Business ₹39,999 → Enterprise)", "Per-plan monthly credits and weekly image limits", "Razorpay kept as an automatic fallback"] },
  { v: "6.4.0", date: "Earlier", items: ["Workforce wheel now has pinch-to-zoom and smooth animated zoom/fit", "Tap a department to glide-focus into its branch; tap again to open it", "14 more department agents — 300+ agents in total"] },
  { v: "6.3.0", date: "Earlier", items: ["Interactive Workforce wheel — pan, zoom & tap the whole AI org chart", "Second brain at the centre; departments branch out; tap any node to run that agent", "Activated agents light up on the map", "14 more department agents — the workforce keeps deepening"] },
  { v: "6.2.0", date: "Earlier", items: ["35+ new department agents — deeper coverage across all 7 functions", "Sales battlecards, ROI justifications, stakeholder maps, win-backs, runbooks, collections & more", "The workforce keeps growing toward a full 137-job org chart"] },
  { v: "6.1.0", date: "Earlier", items: ["Setup Roadmap — a guided, auto-tracked path to a live AI workforce", "Steps light up as you build your brain, run agents, activate departments & invite your team", "Deploy-first / second / third, tracked from your real data"] },
  { v: "6.0.0", date: "Earlier", items: ["Cortex Workforce — a complete AI org chart across 7 departments", "50+ new department agents (Sales, Deals, Marketing, Operations, Intelligence, Customer, Back Office), all runnable", "Every agent plugs into your second brain (Cortex Memory)", "Audit engine — Cortex marks a deploy-first roadmap for your business", "Live activation map that lights up as you run agents", "250+ agents across 7 departments and 26 industries"] },
  { v: "5.4.0", date: "Earlier", items: ["Gratuity calculator (Payment of Gratuity Act)", "EPF & ESI contribution calculator (employee + employer split)", "Advance Tax planner — quarterly instalments & due dates", "Prepay vs Invest decision tool", "Rent vs Buy for office or property", "110+ modules"] },
  { v: "5.3.0", date: "Earlier", items: ["Free trial is now 3 days with a small one-time credit grant — enough to try, not to live on", "Daily upgrade nudge during the trial: a friendly once-a-day pop-up to convert", "After the trial, the paywall requires a plan; existing trials keep their end date", "Trial credits are minimal by design; paid plans get their full monthly allowance"] },
  { v: "5.2.0", date: "Earlier", items: ["Image generation is now a premium, protected feature", "Free trial gives a small weekly taste of image agents — then upgrade to continue", "Per-plan weekly image limits; suspended/expired workspaces are blocked", "Abuse-proof: entitlement checked server-side, fails closed, API key never exposed"] },
  { v: "5.1.0", date: "Earlier", items: ["Image agents are live — 3D mockup, material swap, sharpen & cleanup now generate via Google Gemini (free key)", "Upload a sketch or photo → edit it; download results as PNG; revise in one line", "10 more industries: pharmacy, electronics, furniture, grocery, events, photography, pet care, interior, printing, footwear", "26 industries · 200+ agents in total"] },
  { v: "5.0.0", date: "Earlier", items: ["AI Agents platform — 90+ ready agents across 16 industries", "Jewellery pack: merchandising brief (sketch → spec), stone-plot layout, collection planner, costing", "Every agent: run → approve → revise → export (PDF / Markdown), grounded in your memory", "Cortex builds brand-new custom agents for your exact business, on its own", "Visual & video agents (3D mockup, material swap, deblur, UGC video) ready to activate with a generation provider"] },
  { v: "4.3.0", date: "Earlier", items: ["Appraisal & Hike Planner — distribute a raise budget across bands", "GST Late Fee & Interest calculator", "Marketing Budget & ROAS allocator across channels", "Landing page refreshed — 100+ modules, Cortex Memory front-and-centre"] },
  { v: "4.2.0", date: "Earlier", items: ["Export your entire memory (JSON + Markdown) — your data, always portable", "Cash Conversion Cycle — DIO + DSO − DPO with cash-locked estimate", "Net Worth & Balance Sheet builder", "100+ modules"] },
  { v: "4.1.0", date: "Earlier", items: ["Teach Cortex — one click ingests your customers, team, KPIs & insights into memory", "\"Remember this\" on any AI CEO chat answer — save it to long-term memory", "Auto-builds the entity graph from your real business data"] },
  { v: "4.0.0", date: "Earlier", items: ["Cortex Memory — a permanent, evolving memory for your AI COO", "Every AI action (chat, reports, forecasts, strategy) is now grounded in what Cortex remembers", "Capture facts, decisions & preferences; extract memories from any pasted text", "Knowledge graph of people, customers, vendors & products", "A living, auto-synthesized company profile", "Pin, supersede and cluster memories into themes — the memory layer, built in"] },
  { v: "3.5.0", date: "Earlier", items: ["AI credit metering — every AI action now draws from a credit balance", "Monthly plan allowance auto-tops-up (Starter 500 → Premium 15k, Enterprise unlimited)", "Usage & Credits page: balance, 14-day usage chart, full history, cost table", "Buy credit top-up packs (Razorpay); low-balance warning banner", "Out-of-credit calls are blocked cleanly with a top-up prompt", "Every debit/credit is logged to an auditable ledger"] },
  { v: "3.4.0", date: "Earlier", items: ["Super Admin can now manage any customer: change plan, subscription status, credits and trial", "Add, revoke or set a workspace's credit balance", "Suspend / cancel instantly locks a customer behind the paywall; Active restores it", "Extend a trial by +14 or +30 days in one click", "Your own portfolio workspaces are never gated"] },
  { v: "3.3.0", date: "Earlier", items: ["Payables & DPO with an early-payment-discount decision", "Inventory turnover, DIO and annual holding cost", "GST ITC set-off — net cash payable by CGST/SGST/IGST head", "DSCR & loan eligibility estimator", "Billable rate calculator for services businesses", "95+ modules"] },
  { v: "3.2.0", date: "Earlier", items: ["Cash Runway & Burn — months of runway + out-of-cash date", "Receivables & DSO aging with a chase-first priority list", "TDS calculator across common India sections (194C/J/I/H/Q…)", "Buy vs Lease — present-value decision on big assets", "Customer Lifetime Value with LTV:CAC and payback", "Unit Economics now shows profit sensitivity to volume", "90+ modules"] },
  { v: "3.1.0", date: "Earlier", items: ["Markup ↔ margin converter with keystone & margin quick-sets", "Break-even by product mix (blended contribution margin)", "Investment growth — SIP & lumpsum future value", "Debt payoff planner — avalanche vs snowball", "Printable quotation builder with validity & terms", "85+ modules"] },
  { v: "3.0.0", date: "Earlier", items: ["Financial ratios analyzer (liquidity, leverage, returns)", "Depreciation schedule (SLM & WDV)", "Income tax estimator — new vs old regime", "GST calculator (add/remove + CGST/SGST/IGST)", "Multi-currency converter", "80+ modules · milestone release"] },
  { v: "2.9.0", date: "Earlier", items: ["Customer RFM segmentation with AI actions", "Loan amortization schedule (principal vs interest)", "Sales commission calculator with accelerators", "A/B test significance (two-proportion z-test)", "Inventory ABC (Pareto) analysis", "Request-access flow with email notifications"] },
  { v: "2.8.0", date: "Earlier", items: ["Real 14-day free trial — enforced, not cosmetic", "Countdown banner + hard paywall when the trial ends", "Payment activates the subscription and lifts the paywall", "Refer & Earn program with shareable links", "Futuristic landing page with all features listed"] },
  { v: "2.6.0", date: "Earlier", items: ["Integration marketplace expanded to 60+ tools", "Odoo, Cashfree, PayU, MSG91, Gupshup, Freshdesk, Intercom, Calendly & more", "\"Custom API key\" — store a key for any tool, encrypted", "Live connection tests for SendGrid, Brevo, Calendly, Intercom", "Higher integration limits per plan"] },
  { v: "2.5.0", date: "Earlier", items: ["Payroll & CTC → take-home calculator (India)", "Compliance calendar of statutory due dates", "Cap-table & dilution simulator", "Marketing funnel + ROI/payback calculators", "AI contract review & customer account plans", "2 new AI reasoning modes (contract, account)"] },
  { v: "2.4.0", date: "Earlier", items: ["P&L Builder — live income statement with all three margins", "Discount Impact — the real volume a price cut needs", "AI Playbooks — one-click turnaround, growth & cost plans", "Save any playbook to your workspace"] },
  { v: "2.3.0", date: "Earlier", items: ["KPI Alert rules — get warned when a metric crosses your line", "Action Board — kanban with one-click AI task generation", "Decision Journal with an AI devil's advocate", "New critique reasoning mode", "\"Do not reply\" notice + reply-to on campaign emails"] },
  { v: "2.2.0", date: "Earlier", items: ["Fully branded email template (header, footer, badges, legal)", "Inbound reply capture with Svix-verified webhooks", "Replies inbox with unread tracking + campaign linking", "Token-based open/click tracking", "One-click webhook setup + reply simulator"] },
  { v: "2.1.0", date: "Earlier", items: ["Email campaigns — reusable templates with {{merge}} tokens", "Personalised mail-merge to selected leads (name/email swapped per person)", "Open tracking (pixel) and click tracking (redirect)", "Per-campaign insights: open rate, click rate, per-recipient outcomes", "AI email drafting inside the composer"] },
  { v: "2.0.0", date: "Earlier", items: ["Integration marketplace — 27 tools across 7 categories", "AES-256-GCM encryption for all stored API keys", "Credentials verified with the provider before saving", "Per-plan integration gating and quotas", "Admin-only access with row-level security"] },
  { v: "1.9.0", date: "Earlier", items: ["Email Console — send mail from the dashboard, AI-draft, templates", "Live delivery log + sending-domain status from Resend", "Captured leads visible alongside email", "Embeddable live uptime badge at /api/badge"] },
  { v: "1.8.0", date: "Earlier", items: ["AI Proposal & Quote generator", "Team capacity & utilisation planner", "Business valuation (multiples + DCF)", "NPS & customer sentiment tracker", "2 new AI reasoning modes (proposal, valuation)"] },
  { v: "1.7.0", date: "Earlier", items: ["Workspace switcher — run multiple businesses from one login", "SaaS metrics: MRR, ARR, LTV:CAC, CAC payback, retention projection", "Project & client profitability with effective hourly rate", "13-week rolling cash flow with crunch warning", "Platform Super Admin console"] },
  { v: "1.6.0", date: "Earlier", items: ["Inventory Reorder Optimizer (EOQ + safety stock)", "WhatsApp Broadcast Composer with wa.me links", "Sales Target Planner (annual → monthly, per-rep)", "Board Deck Generator", "Cost Optimizer", "3 new AI reasoning modes (broadcast, board, costs)"] },
  { v: "1.5.0", date: "Earlier", items: ["Working-capital / cash-conversion-cycle simulator", "Unit economics & break-even calculator", "Loan / EMI calculator with AI CFO advice", "GST invoice generator with PDF export", "Vendor Scorecard & SOP Builder", "3 new AI reasoning modes (loan, vendor, SOP)"] },
  { v: "1.4.0", date: "Earlier", items: ["Investor & Board Update generator", "Marketing Studio — full campaign kits in one click", "Competitor Intelligence battlecards", "Hindi & Hinglish replies in the AI CEO chat", "Email now delivers from your verified domain"] },
  { v: "1.3.0", date: "Earlier", items: ["Daily CEO Brief — generated + emailed to your inbox", "Customer Churn Predictor with editable risk model", "Negotiation Coach & Hiring/Org Advisor", "GST & Compliance assistant with filing calendar", "New GST-aware AI reasoning mode"] },
  { v: "1.2.0", date: "Earlier", items: ["Foresight Suite: 90-day AI forecasting + interactive what-if scenario planner", "AI Action Center — every decision ranked by impact", "Goals & OKR tracker with live progress rings", "Risk Radar, Industry Benchmarks & AI Pricing Optimizer", "Voice input in the AI CEO chat", "8 new CFO-grade AI reasoning modes"] },
  { v: "1.1.0", date: "Earlier", items: ["Global AI Copilot on every page", "Owner analytics dashboard", "Public API + webhooks", "Deals pipeline, CRM & lead scoring", "White-label theming, billing & Razorpay", "Installable app with forced-update flow", "Public status page & shareable reports"] },
  { v: "1.0.0", date: "Launch", items: ["13 AI modules & streaming AI CEO chat", "Business Health Dashboard + Cortex Score", "AI Reports, Documents, Meetings, Market, Strategy", "Approvals, workflows, activity log", "CSV/Excel/PDF import & export", "Supabase auth + RLS, Groq AI"] },
];

/** Numeric semver-ish compare of "a.b.c" strings. Returns 1 / 0 / -1. */
export function cmpVersion(a: string, b: string): number {
  const pa = a.split(".").map((n) => parseInt(n, 10) || 0);
  const pb = b.split(".").map((n) => parseInt(n, 10) || 0);
  for (let i = 0; i < 3; i++) {
    const d = (pa[i] || 0) - (pb[i] || 0);
    if (d) return d > 0 ? 1 : -1;
  }
  return 0;
}

/**
 * Releases newer than `version`. If `version` is null (first-ever email),
 * return the most recent `maxFirst` releases so the first edition is substantive.
 */
export function releasesSince(version: string | null, maxFirst = 5): Release[] {
  if (!version) return RELEASES.slice(0, maxFirst);
  return RELEASES.filter((r) => cmpVersion(r.v, version) > 0);
}
