import {
  LayoutDashboard, MessageSquare, TrendingUp, Wallet, Factory, Boxes,
  Users, Globe, Brain, FileText, Video, Workflow, Shield, Settings, FileBarChart, CheckCircle2, Upload, Sparkles, Database, Plug, Inbox, Contact, Activity, KanbanSquare, Code2, Bot, CreditCard, BarChart3,
  LineChart, Target, ListChecks, Gauge, ShieldAlert, BadgeIndianRupee,
  Sunrise, Handshake, UserPlus, Receipt, UserMinus,
  Presentation, Megaphone, Swords,
  Coins, Calculator, Landmark, FileSignature, Truck, ClipboardList,
  Warehouse, Radio, Crosshair, MonitorPlay, PiggyBank,
  Repeat, Briefcase, CalendarClock,
  FileCheck2, GaugeCircle, Scale, Smile,
  BellRing, ListTodo, Gavel,
  FileSpreadsheet, Percent, BookOpen,
  Banknote, CalendarCheck, PieChart, Filter, CircleDollarSign, ScrollText, UserSearch,
  Gift, Layers, Table2, HandCoins, FlaskConical, ListOrdered,
  Sigma, Building2, IndianRupee, ArrowLeftRight, Divide,
  Sprout, Anchor, Tag, Equal, ClipboardCheck,
  Flame, Hourglass, Stamp, GitCompare, Gem,
  ReceiptText, PackageSearch, Blocks, ShieldCheck, Timer,
  Fuel, BrainCircuit, Vault, RotateCw,
  Award, AlarmClock, Radar,
  HeartHandshake, Umbrella, CalendarDays, Repeat2, House,
  Network, Telescope
} from "lucide-react";

export const NAV = [
  { href: "/dashboard", label: "Business Health", icon: LayoutDashboard, group: "Overview" },
  { href: "/chat", label: "AI CEO Chat", icon: MessageSquare, group: "Overview" },
  { href: "/deepdive", label: "Cortex Deep Dive", icon: Telescope, group: "Overview" },
  { href: "/act", label: "AI Outreach", icon: Megaphone, group: "Overview" },
  { href: "/memory", label: "Cortex Memory", icon: BrainCircuit, group: "Overview" },
  { href: "/agents", label: "AI Agents", icon: Bot, group: "Overview" },
  { href: "/workforce", label: "Cortex Workforce", icon: Network, group: "Overview" },
  { href: "/roadmap", label: "Setup Roadmap", icon: ListChecks, group: "Overview" },
  { href: "/analytics", label: "Analytics", icon: BarChart3, group: "Overview" },
  { href: "/sales", label: "Sales", icon: TrendingUp, group: "Intelligence" },
  { href: "/finance", label: "Finance", icon: Wallet, group: "Intelligence" },
  { href: "/bank", label: "Bank Statement", icon: Landmark, group: "Intelligence" },
  { href: "/production", label: "Production", icon: Factory, group: "Intelligence" },
  { href: "/inventory", label: "Inventory", icon: Boxes, group: "Intelligence" },
  { href: "/hr", label: "HR", icon: Users, group: "Intelligence" },
  { href: "/market", label: "Market", icon: Globe, group: "Intelligence" },
  { href: "/visibility", label: "AI Visibility", icon: Radar, group: "Intelligence" },
  { href: "/customers", label: "Customers", icon: Contact, group: "Intelligence" },
  { href: "/accounts", label: "Account Plans", icon: UserSearch, group: "Intelligence" },
  { href: "/funnel", label: "Marketing Funnel", icon: Filter, group: "Intelligence" },
  { href: "/adbudget", label: "Ad Budget & ROAS", icon: Radar, group: "Intelligence" },
  { href: "/rfm", label: "Customer Segments", icon: Layers, group: "Intelligence" },
  { href: "/ltv", label: "Lifetime Value", icon: Gem, group: "Intelligence" },
  { href: "/inventory-turns", label: "Inventory Turnover", icon: PackageSearch, group: "Intelligence" },
  { href: "/abc", label: "Inventory ABC", icon: ListOrdered, group: "Intelligence" },
  { href: "/abtest", label: "A/B Test Stats", icon: FlaskConical, group: "Intelligence" },
  { href: "/pipeline", label: "Deals Pipeline", icon: KanbanSquare, group: "Intelligence" },
  { href: "/churn", label: "Churn Predictor", icon: UserMinus, group: "Intelligence" },
  { href: "/reorder", label: "Reorder Optimizer", icon: Warehouse, group: "Intelligence" },
  { href: "/targets", label: "Sales Targets", icon: Crosshair, group: "Intelligence" },
  { href: "/strategy", label: "Strategy Consultant", icon: Brain, group: "Advisory" },
  { href: "/documents", label: "Documents", icon: FileText, group: "Advisory" },
  { href: "/meetings", label: "Meetings", icon: Video, group: "Advisory" },
  { href: "/reports", label: "Reports", icon: FileBarChart, group: "Advisory" },
  { href: "/negotiate", label: "Negotiation Coach", icon: Handshake, group: "Advisory" },
  { href: "/hiring", label: "Hiring Advisor", icon: UserPlus, group: "Advisory" },
  { href: "/gst", label: "GST & Compliance", icon: Receipt, group: "Advisory" },
  { href: "/gst-reader", label: "GST Return Reader", icon: ReceiptText, group: "Advisory" },
  { href: "/compliance", label: "Compliance Calendar", icon: CalendarCheck, group: "Advisory" },
  { href: "/contracts", label: "Contract Review", icon: ScrollText, group: "Advisory" },
  { href: "/investor", label: "Investor Update", icon: Presentation, group: "Advisory" },
  { href: "/marketing", label: "Marketing Studio", icon: Megaphone, group: "Advisory" },
  { href: "/competitors", label: "Competitor Intel", icon: Swords, group: "Advisory" },
  { href: "/proposals", label: "Proposals & Quotes", icon: FileCheck2, group: "Advisory" },
  { href: "/quote", label: "Quotation Builder", icon: ClipboardCheck, group: "Advisory" },
  { href: "/vendors", label: "Vendor Scorecard", icon: Truck, group: "Advisory" },
  { href: "/sops", label: "SOP Builder", icon: ClipboardList, group: "Advisory" },
  { href: "/broadcast", label: "WhatsApp Broadcast", icon: Radio, group: "Advisory" },
  { href: "/boardroom", label: "Board Deck", icon: MonitorPlay, group: "Advisory" },
  { href: "/cashflow", label: "Cash Flow", icon: Coins, group: "Money" },
  { href: "/unit-economics", label: "Unit Economics", icon: Calculator, group: "Money" },
  { href: "/funding", label: "Funding & Loans", icon: Landmark, group: "Money" },
  { href: "/invoice", label: "GST Invoice", icon: FileSignature, group: "Money" },
  { href: "/costs", label: "Cost Optimizer", icon: PiggyBank, group: "Money" },
  { href: "/pnl", label: "P&L Builder", icon: FileSpreadsheet, group: "Money" },
  { href: "/discount", label: "Discount Impact", icon: Percent, group: "Money" },
  { href: "/roi", label: "ROI & Payback", icon: CircleDollarSign, group: "Money" },
  { href: "/amortization", label: "Loan Schedule", icon: Table2, group: "Money" },
  { href: "/commission", label: "Sales Commission", icon: HandCoins, group: "Money" },
  { href: "/payroll", label: "Payroll & CTC", icon: Banknote, group: "Money" },
  { href: "/appraisal", label: "Appraisal & Hikes", icon: Award, group: "Money" },
  { href: "/gst-latefee", label: "GST Late Fee", icon: AlarmClock, group: "Money" },
  { href: "/gratuity", label: "Gratuity", icon: HeartHandshake, group: "Money" },
  { href: "/epf", label: "EPF & ESI", icon: Umbrella, group: "Money" },
  { href: "/advance-tax", label: "Advance Tax", icon: CalendarDays, group: "Money" },
  { href: "/prepay", label: "Prepay vs Invest", icon: Repeat2, group: "Money" },
  { href: "/rentvsbuy", label: "Rent vs Buy", icon: House, group: "Money" },
  { href: "/captable", label: "Cap Table", icon: PieChart, group: "Money" },
  { href: "/cash13", label: "13-Week Cash Flow", icon: CalendarClock, group: "Money" },
  { href: "/saas", label: "SaaS Metrics", icon: Repeat, group: "Money" },
  { href: "/projects", label: "Project Profitability", icon: Briefcase, group: "Money" },
  { href: "/valuation", label: "Business Valuation", icon: Scale, group: "Money" },
  { href: "/ratios", label: "Financial Ratios", icon: Sigma, group: "Money" },
  { href: "/tax", label: "Income Tax", icon: IndianRupee, group: "Money" },
  { href: "/depreciation", label: "Depreciation", icon: Building2, group: "Money" },
  { href: "/gst-calc", label: "GST Calculator", icon: Divide, group: "Money" },
  { href: "/currency", label: "Currency", icon: ArrowLeftRight, group: "Money" },
  { href: "/markup", label: "Markup & Margin", icon: Tag, group: "Money" },
  { href: "/breakeven", label: "Break-even Mix", icon: Equal, group: "Money" },
  { href: "/sip", label: "Investment Growth", icon: Sprout, group: "Money" },
  { href: "/debt", label: "Debt Payoff", icon: Anchor, group: "Money" },
  { href: "/runway", label: "Cash Runway", icon: Flame, group: "Money" },
  { href: "/receivables", label: "Receivables & DSO", icon: Hourglass, group: "Money" },
  { href: "/tds", label: "TDS Calculator", icon: Stamp, group: "Money" },
  { href: "/buyvslease", label: "Buy vs Lease", icon: GitCompare, group: "Money" },
  { href: "/payables", label: "Payables & DPO", icon: ReceiptText, group: "Money" },
  { href: "/itc", label: "GST ITC Set-off", icon: Blocks, group: "Money" },
  { href: "/dscr", label: "DSCR & Loan Fit", icon: ShieldCheck, group: "Money" },
  { href: "/rate-card", label: "Billable Rate", icon: Timer, group: "Money" },
  { href: "/ccc", label: "Cash Conversion Cycle", icon: RotateCw, group: "Money" },
  { href: "/networth", label: "Net Worth & Balance", icon: Vault, group: "Money" },
  { href: "/capacity", label: "Team Capacity", icon: GaugeCircle, group: "Intelligence" },
  { href: "/nps", label: "NPS & Sentiment", icon: Smile, group: "Intelligence" },
  { href: "/brief", label: "Daily Brief", icon: Sunrise, group: "Foresight" },
  { href: "/forecast", label: "Forecasting", icon: LineChart, group: "Foresight" },
  { href: "/action-center", label: "Action Center", icon: ListChecks, group: "Foresight" },
  { href: "/alerts", label: "KPI Alerts", icon: BellRing, group: "Foresight" },
  { href: "/tasks", label: "Action Board", icon: ListTodo, group: "Foresight" },
  { href: "/decisions", label: "Decision Journal", icon: Gavel, group: "Advisory" },
  { href: "/playbooks", label: "AI Playbooks", icon: BookOpen, group: "Advisory" },
  { href: "/goals", label: "Goals & OKRs", icon: Target, group: "Foresight" },
  { href: "/risks", label: "Risk Radar", icon: ShieldAlert, group: "Foresight" },
  { href: "/benchmarks", label: "Benchmarks", icon: Gauge, group: "Foresight" },
  { href: "/pricing-optimizer", label: "Pricing Optimizer", icon: BadgeIndianRupee, group: "Foresight" },
  { href: "/workflows", label: "Workflows", icon: Workflow, group: "Automation" },
  { href: "/approvals", label: "Approvals", icon: CheckCircle2, group: "Automation" },
  { href: "/import", label: "Import data", icon: Upload, group: "Automation" },
  { href: "/data", label: "Data Explorer", icon: Database, group: "Automation" },
  { href: "/integrations", label: "Integrations", icon: Plug, group: "Automation" },
  { href: "/leads", label: "Leads", icon: Inbox, group: "Automation" },
  { href: "/activity", label: "Activity", icon: Activity, group: "Automation" },
  { href: "/developers", label: "Developers · API", icon: Code2, group: "Automation" },
  { href: "/autopilot", label: "AI Autopilot", icon: Bot, group: "Automation" },
  { href: "/billing", label: "Billing & Plan", icon: CreditCard, group: "Automation" },
  { href: "/usage", label: "Usage & Credits", icon: Fuel, group: "Automation" },
  { href: "/referrals", label: "Refer & Earn", icon: Gift, group: "Automation" },
  { href: "/admin", label: "Admin & Access", icon: Shield, group: "Automation" },
  { href: "/settings", label: "Settings", icon: Settings, group: "Automation" },
  { href: "/pricing", label: "Pricing & plans", icon: Sparkles, group: "Automation" },
] as const;
