import "server-only";
import { serviceClient } from "@/lib/supabase/server";
import { REFERRAL_REWARD_CREDITS } from "@/lib/config";
// Pure helpers live in referral-shared so middleware (Edge runtime) can use
// them without pulling next/headers in through serviceClient.
import { normalizeCode } from "@/lib/referral-shared";
export { REFERRAL_COOKIE, REFERRAL_COOKIE_DAYS, normalizeCode } from "@/lib/referral-shared";

/**
 * The referral programme.
 *
 * Three touch points, deliberately kept small:
 *
 *   1. middleware.ts sees `?ref=CODE` on any entry URL and drops a cookie.
 *   2. ensureWorkspace() calls attachReferral() when a NEW workspace is created,
 *      turning that cookie into a 'pending' row.
 *   3. settleOrder() calls rewardReferral() when a plan actually goes active,
 *      which pays both sides once.
 *
 * Everything that grants value runs through the service-role client and the
 * database function. Nothing here is reachable from the browser: the
 * `referrals` table has a SELECT policy and no write policy, and
 * `cortex_reward_referral` is revoked from `authenticated`.
 *
 * Every function swallows its own errors. A referral is a nice-to-have; it must
 * never be the reason a signup fails or a paid plan does not activate.
 */

export type ReferralRow = {
  id: string;
  status: string;
  created_at: string;
  rewarded_at: string | null;
  reward_credits: number;
  referred_name: string | null;
};

/** This workspace's own code, for sharing. Generated by the DB on insert. */
export async function getReferralCode(orgId: string): Promise<string | null> {
  const svc = serviceClient();
  if (!svc) return null;
  try {
    const { data } = await svc.from("organizations").select("referral_code").eq("id", orgId).single();
    return (data as any)?.referral_code ?? null;
  } catch { return null; }
}

/**
 * Record that `newOrgId` was referred by whoever owns `code`.
 *
 * Called once, at workspace creation. Returns true only if a row was written.
 *
 * The guards here are the programme's integrity: an unknown code is ignored, a
 * workspace cannot refer itself, and the referred workspace is UNIQUE in the
 * table so a second call can never create a second payable row.
 */
export async function attachReferral(newOrgId: string, rawCode: string | null): Promise<boolean> {
  const code = normalizeCode(rawCode);
  if (!code) return false;
  const svc = serviceClient();
  if (!svc) return false;

  try {
    const { data: owner } = await svc
      .from("organizations").select("id").eq("referral_code", code).single();
    const referrer = (owner as any)?.id as string | undefined;
    // Unknown code, or someone pasting their own link into their own signup.
    if (!referrer || referrer === newOrgId) return false;

    const { error } = await svc.from("referrals").insert({
      referrer_org_id: referrer,
      referred_org_id: newOrgId,
      code,
    });
    // Unique violation = already referred. Not an error worth surfacing.
    return !error;
  } catch { return false; }
}

/**
 * Pay both sides, once, when a referred workspace starts paying.
 *
 * Idempotent by construction: the SQL function locks the row and only acts on a
 * 'pending' one, so a duplicated Cashfree webhook or next month's renewal
 * returns 0 rather than granting again.
 */
export async function rewardReferral(referredOrgId: string): Promise<number> {
  const svc = serviceClient();
  if (!svc) return 0;
  try {
    const { data, error } = await svc.rpc("cortex_reward_referral", {
      p_referred: referredOrgId,
      p_credits: REFERRAL_REWARD_CREDITS,
    });
    if (error) return 0;
    return Number(data) || 0;
  } catch { return 0; }
}

/** Everyone this workspace has referred, newest first, for the /referrals page. */
export async function listReferrals(orgId: string): Promise<ReferralRow[]> {
  const svc = serviceClient();
  if (!svc) return [];
  try {
    const { data } = await svc
      .from("referrals")
      .select("id, status, created_at, rewarded_at, reward_credits, referred:referred_org_id (name)")
      .eq("referrer_org_id", orgId)
      .order("created_at", { ascending: false })
      .limit(100);
    return (data || []).map((r: any) => ({
      id: r.id,
      status: r.status,
      created_at: r.created_at,
      rewarded_at: r.rewarded_at,
      reward_credits: Number(r.reward_credits) || 0,
      /*
        The other business's NAME only. Never their email, plan or spend — the
        referrer is not entitled to another company's account details just
        because they sent a link.
      */
      referred_name: r.referred?.name ?? null,
    }));
  } catch { return []; }
}
