import "server-only";
import { serviceClient } from "@/lib/supabase/server";
import { generateFor } from "@/lib/ai/cortex";
import { sendEmail } from "@/lib/email";
import { brandFrom } from "@/lib/branded-email";
import { mdToHtml } from "@/lib/utils";
import { emitQuietly } from "@/lib/webhooks";

/**
 * Scheduled reports — "Custom dashboards & auto-reports" on the Premium plan,
 * which had no scheduler behind it.
 *
 * Runs off the single daily cron (Vercel Hobby allows one), and each report
 * decides for itself whether it's due. `last_sent` is the guard, so a cron that
 * fires twice in a day cannot send twice.
 */

const DAY = 86_400_000;

function isDue(cadence: string, lastSent: string | null): boolean {
  if (!lastSent) return true;
  const since = Date.now() - new Date(lastSent).getTime();
  if (!Number.isFinite(since)) return true;
  switch (cadence) {
    case "daily":   return since >= 0.9 * DAY;     // tolerate cron jitter
    case "monthly": return since >= 28 * DAY;
    case "weekly":
    default:        return since >= 6.5 * DAY;
  }
}

async function ownerEmail(svc: any, orgId: string): Promise<string | null> {
  try {
    const { data: mems } = await svc.from("memberships")
      .select("user_id, role").eq("org_id", orgId).in("role", ["owner", "admin"]).limit(3);
    for (const m of ((mems as any[]) || []).sort((a) => (a.role === "owner" ? -1 : 1))) {
      const { data } = await svc.auth.admin.getUserById(m.user_id);
      if (data?.user?.email) return data.user.email;
    }
  } catch { /* fall through */ }
  return null;
}

/** Business snapshot for one org, without going through the request-scoped helper. */
async function contextFor(svc: any, orgId: string): Promise<string | null> {
  const { data } = await svc.from("health_metrics")
    .select("label,value,unit,delta_pct,status").eq("org_id", orgId);
  const m = (data as any[]) || [];
  if (!m.length) return null;   // nothing real to report on — skip rather than invent
  return "KEY METRICS:\n" + m.map((x) =>
    `- ${x.label}: ${x.value}${x.unit === "INR" ? " INR" : " " + (x.unit || "")} (${x.delta_pct > 0 ? "+" : ""}${x.delta_pct}%, ${x.status})`).join("\n");
}

export type ReportRun = { checked: number; sent: number; skipped: number; errors: number };

export async function runScheduledReports(): Promise<ReportRun> {
  const out: ReportRun = { checked: 0, sent: 0, skipped: 0, errors: 0 };
  const svc = serviceClient();
  if (!svc) return out;

  let rows: any[] = [];
  try {
    const { data } = await svc.from("scheduled_reports")
      .select("id, org_id, mode, cadence, send_to, last_sent").eq("is_active", true).limit(300);
    rows = (data as any[]) || [];
  } catch { return out; }

  for (const r of rows) {
    out.checked++;
    if (!isDue(r.cadence, r.last_sent)) { out.skipped++; continue; }

    const context = await contextFor(svc, r.org_id);
    if (!context) { out.skipped++; continue; }   // empty workspace: nothing honest to send

    const to = r.send_to || (await ownerEmail(svc, r.org_id));
    if (!to) { out.errors++; continue; }

    let body = "";
    try { body = await generateFor(String(r.mode || "brief"), "", context); } catch { /* handled below */ }
    if (!body || /^I couldn't reach the AI engine/.test(body)) { out.errors++; continue; }

    const title = `Your ${r.cadence} ${r.mode} — MNB Cortex`;
    const html = `<div style="font-family:system-ui,sans-serif;max-width:620px;margin:auto">
      <h2 style="color:#2f6b54">${title}</h2>
      <div style="font-size:14px;line-height:1.65;color:#111">${mdToHtml(body)}</div>
      <p style="font-size:12px;color:#888;margin-top:22px">Generated by MNB Cortex — your AI COO. Manage or stop this report under Reports.</p>
    </div>`;

    const res = await sendEmail(to, title, html, { from: brandFrom() });
    if (res.sent) {
      out.sent++;
      // last_sent is the idempotency guard — only advance it on a real send.
      try { await svc.from("scheduled_reports").update({ last_sent: new Date().toISOString() }).eq("id", r.id); } catch {}
      emitQuietly(r.org_id, "report.generated", { mode: r.mode, cadence: r.cadence, to });
    } else {
      out.errors++;
    }
  }

  return out;
}
