import Link from "next/link";
import { APP_VERSION } from "@/lib/config";
import { Logo } from "@/components/logo";
export const metadata = { title: "Changelog — MNB Cortex" };
const releases = [
  { v: "6.0.0", date: "Latest", items: ["Cortex Workforce — a complete AI org chart across 7 departments", "50+ new department agents (Sales, Deals, Marketing, Operations, Intelligence, Customer, Back Office), all runnable", "Every agent plugs into your second brain (Cortex Memory)", "Audit engine — Cortex marks a deploy-first roadmap for your business", "Live activation map that lights up as you run agents", "250+ agents across 7 departments and 26 industries"] },
  { v: "5.4.0", date: "Earlier", items: ["Gratuity calculator (Payment of Gratuity Act)", "EPF & ESI contribution calculator (employee + employer split)", "Advance Tax planner — quarterly instalments & due dates", "Prepay vs Invest decision tool", "Rent vs Buy for office or property", "110+ modules"] },
  { v: "5.3.0", date: "Earlier", items: ["Free trial is now 3 days with a small one-time credit grant — enough to try, not to live on", "Daily upgrade nudge during the trial: a friendly once-a-day pop-up to convert", "After the trial, the paywall requires a plan; existing trials keep their end date", "Trial credits are minimal by design; paid plans get their full monthly allowance"] },
  { v: "5.2.0", date: "Earlier", items: ["Image generation is now a premium, protected feature", "Free trial gives a small weekly taste of image agents — then upgrade to continue", "Per-plan weekly image limits; suspended/expired workspaces are blocked", "Abuse-proof: entitlement checked server-side, fails closed, API key never exposed"] },
  { v: "5.1.0", date: "Earlier", items: ["Image agents are live — 3D mockup, material swap, sharpen & cleanup now generate via Google Gemini (free key)", "Upload a sketch or photo → edit it; download results as PNG; revise in one line", "10 more industries: pharmacy, electronics, furniture, grocery, events, photography, pet care, interior, printing, footwear", "26 industries · 200+ agents in total"] },
  { v: "5.0.0", date: "Earlier", items: ["AI Agents platform — 90+ ready agents across 16 industries", "Jewellery pack: merchandising brief (sketch → spec), stone-plot layout, collection planner, costing", "Every agent: run → approve → revise → export (PDF / Markdown), grounded in your memory", "Cortex builds brand-new custom agents for your exact business, on its own", "Visual & video agents (3D mockup, material swap, deblur, UGC video) ready to activate with a generation provider"] },
  { v: "4.3.0", date: "Earlier", items: ["Appraisal & Hike Planner — distribute a raise budget across bands", "GST Late Fee & Interest calculator", "Marketing Budget & ROAS allocator across channels", "Landing page refreshed — 100+ modules, Cortex Memory front-and-centre"] },
  { v: "4.2.0", date: "Earlier", items: ["Export your entire memory (JSON + Markdown) — your data, always portable", "Cash Conversion Cycle — DIO + DSO − DPO with cash-locked estimate", "Net Worth & Balance Sheet builder", "100+ modules"] },
  { v: "4.1.0", date: "Earlier", items: ["Teach Cortex — one click ingests your customers, team, KPIs & insights into memory", "\"Remember this\" on any AI CEO chat answer — save it to long-term memory", "Auto-builds the entity graph from your real business data"] },
  { v: "4.0.0", date: "Earlier", items: ["Cortex Memory — a permanent, evolving memory for your AI COO", "Every AI action (chat, reports, forecasts, strategy) is now grounded in what Cortex remembers", "Capture facts, decisions & preferences; extract memories from any pasted text", "Knowledge graph of people, customers, vendors & products", "A living, auto-synthesized company profile", "Pin, supersede and cluster memories into themes — the memory layer, built in"] },
  { v: "3.5.0", date: "Earlier", items: ["AI credit metering — every AI action now draws from a credit balance", "Monthly plan allowance auto-tops-up (Starter 500 → Premium 15k, Enterprise unlimited)", "Usage & Credits page: balance, 14-day usage chart, full history, cost table", "Buy credit top-up packs (Razorpay); low-balance warning banner", "Out-of-credit calls are blocked cleanly with a top-up prompt", "Every debit/credit is logged to an auditable ledger"] },
  { v: "3.4.0", date: "Earlier", items: ["Super Admin can now manage any customer: change plan, subscription status, credits and trial", "Add, revoke or set a workspace's credit balance", "Suspend / cancel instantly locks a customer behind the paywall; Active restores it", "Extend a trial by +14 or +30 days in one click", "Your own portfolio workspaces are never gated"] },
  { v: "3.3.0", date: "Earlier", items: ["Payables & DPO with an early-payment-discount decision", "Inventory turnover, DIO and annual holding cost", "GST ITC set-off — net cash payable by CGST/SGST/IGST head", "DSCR & loan eligibility estimator", "Billable rate calculator for services businesses", "95+ modules"] },
  { v: "3.2.0", date: "Earlier", items: ["Cash Runway & Burn — months of runway + out-of-cash date", "Receivables & DSO aging with a chase-first priority list", "TDS calculator across common India sections (194C/J/I/H/Q…)", "Buy vs Lease — present-value decision on big assets", "Customer Lifetime Value with LTV:CAC and payback", "Unit Economics now shows profit sensitivity to volume", "90+ modules"] },
  { v: "3.1.0", date: "Earlier", items: ["Markup ↔ margin converter with keystone & margin quick-sets", "Break-even by product mix (blended contribution margin)", "Investment growth — SIP & lumpsum future value", "Debt payoff planner — avalanche vs snowball", "Printable quotation builder with validity & terms", "85+ modules"] },
  { v: "3.0.0", date: "Earlier", items: ["Financial ratios analyzer (liquidity, leverage, returns)", "Depreciation schedule (SLM & WDV)", "Income tax estimator — new vs old regime", "GST calculator (add/remove + CGST/SGST/IGST)", "Multi-currency converter", "80+ modules · milestone release"] },
  { v: "2.9.0", date: "Earlier", items: ["Customer RFM segmentation with AI actions", "Loan amortization schedule (principal vs interest)", "Sales commission calculator with accelerators", "A/B test significance (two-proportion z-test)", "Inventory ABC (Pareto) analysis", "Request-access flow with email notifications"] },
  { v: "2.8.0", date: "Earlier", items: ["Real 14-day free trial — enforced, not cosmetic", "Countdown banner + hard paywall when the trial ends", "Payment activates the subscription and lifts the paywall", "Refer & Earn program with shareable links", "Futuristic landing page with all features listed"] },
  { v: "2.6.0", date: "Earlier", items: ["Integration marketplace expanded to 60+ tools", "Odoo, Cashfree, PayU, MSG91, Gupshup, Freshdesk, Intercom, Calendly & more", "\"Custom API key\" — store a key for any tool, encrypted", "Live connection tests for SendGrid, Brevo, Calendly, Intercom", "Higher integration limits per plan"] },
  { v: "2.5.0", date: "Earlier", items: ["Payroll & CTC → take-home calculator (India)", "Compliance calendar of statutory due dates", "Cap-table & dilution simulator", "Marketing funnel + ROI/payback calculators", "AI contract review & customer account plans", "2 new AI reasoning modes (contract, account)"] },
  { v: "2.4.0", date: "Earlier", items: ["P&L Builder — live income statement with all three margins", "Discount Impact — the real volume a price cut needs", "AI Playbooks — one-click turnaround, growth & cost plans", "Save any playbook to your workspace"] },
  { v: "2.3.0", date: "Earlier", items: ["KPI Alert rules — get warned when a metric crosses your line", "Action Board — kanban with one-click AI task generation", "Decision Journal with an AI devil's advocate", "New critique reasoning mode", "\"Do not reply\" notice + reply-to on campaign emails"] },
  { v: "2.2.0", date: "Earlier", items: ["Fully branded email template (header, footer, badges, legal)", "Inbound reply capture with Svix-verified webhooks", "Replies inbox with unread tracking + campaign linking", "Token-based open/click tracking", "One-click webhook setup + reply simulator"] },
  { v: "2.1.0", date: "Earlier", items: ["Email campaigns — reusable templates with {{merge}} tokens", "Personalised mail-merge to selected leads (name/email swapped per person)", "Open tracking (pixel) and click tracking (redirect)", "Per-campaign insights: open rate, click rate, per-recipient outcomes", "AI email drafting inside the composer"] },
  { v: "2.0.0", date: "Earlier", items: ["Integration marketplace — 27 tools across 7 categories", "AES-256-GCM encryption for all stored API keys", "Credentials verified with the provider before saving", "Per-plan integration gating and quotas", "Admin-only access with row-level security"] },
  { v: "1.9.0", date: "Earlier", items: ["Email Console — send mail from the dashboard, AI-draft, templates", "Live delivery log + sending-domain status from Resend", "Captured leads visible alongside email", "Embeddable live uptime badge at /api/badge"] },
  { v: "1.8.0", date: "Earlier", items: ["AI Proposal & Quote generator", "Team capacity & utilisation planner", "Business valuation (multiples + DCF)", "NPS & customer sentiment tracker", "2 new AI reasoning modes (proposal, valuation)"] },
  { v: "1.7.0", date: "Earlier", items: ["Workspace switcher — run multiple businesses from one login", "SaaS metrics: MRR, ARR, LTV:CAC, CAC payback, retention projection", "Project & client profitability with effective hourly rate", "13-week rolling cash flow with crunch warning", "Platform Super Admin console"] },
  { v: "1.6.0", date: "Earlier", items: ["Inventory Reorder Optimizer (EOQ + safety stock)", "WhatsApp Broadcast Composer with wa.me links", "Sales Target Planner (annual → monthly, per-rep)", "Board Deck Generator", "Cost Optimizer", "3 new AI reasoning modes (broadcast, board, costs)"] },
  { v: "1.5.0", date: "Earlier", items: ["Working-capital / cash-conversion-cycle simulator", "Unit economics & break-even calculator", "Loan / EMI calculator with AI CFO advice", "GST invoice generator with PDF export", "Vendor Scorecard & SOP Builder", "3 new AI reasoning modes (loan, vendor, SOP)"] },
  { v: "1.4.0", date: "Earlier", items: ["Investor & Board Update generator", "Marketing Studio — full campaign kits in one click", "Competitor Intelligence battlecards", "Hindi & Hinglish replies in the AI CEO chat", "Email now delivers from your verified domain"] },
  { v: "1.3.0", date: "Earlier", items: ["Daily CEO Brief — generated + emailed to your inbox", "Customer Churn Predictor with editable risk model", "Negotiation Coach & Hiring/Org Advisor", "GST & Compliance assistant with filing calendar", "New GST-aware AI reasoning mode"] },
  { v: "1.2.0", date: "Earlier", items: ["Foresight Suite: 90-day AI forecasting + interactive what-if scenario planner", "AI Action Center — every decision ranked by impact", "Goals & OKR tracker with live progress rings", "Risk Radar, Industry Benchmarks & AI Pricing Optimizer", "Voice input in the AI CEO chat", "8 new CFO-grade AI reasoning modes"] },
  { v: "1.1.0", date: "Earlier", items: ["Global AI Copilot on every page", "Owner analytics dashboard", "Public API + webhooks", "Deals pipeline, CRM & lead scoring", "White-label theming, billing & Razorpay", "Installable app with forced-update flow", "Public status page & shareable reports"] },
  { v: "1.0.0", date: "Launch", items: ["13 AI modules & streaming AI CEO chat", "Business Health Dashboard + Cortex Score", "AI Reports, Documents, Meetings, Market, Strategy", "Approvals, workflows, activity log", "CSV/Excel/PDF import & export", "Supabase auth + RLS, Groq AI"] },
];
export default function Changelog() {
  return (
    <main className="min-h-screen">
      <header className="flex items-center justify-between px-6 lg:px-12 h-16 border-b">
        <Link href="/" className="flex items-center gap-2"><Logo size={32} /><span className="font-semibold">MNB Cortex</span></Link>
        <div className="flex gap-4 text-sm"><Link href="/pricing" className="text-muted-foreground hover:text-foreground">Pricing</Link><Link href="/status" className="text-muted-foreground hover:text-foreground">Status</Link></div>
      </header>
      <section className="max-w-2xl mx-auto px-6 py-14">
        <h1 className="text-3xl font-semibold tracking-tight">Changelog</h1>
        <p className="text-muted-foreground mt-1">What's new in MNB Cortex. Current: v{APP_VERSION}</p>
        <div className="mt-10 space-y-10">
          {releases.map((r) => (
            <div key={r.v} className="relative border-l pl-6">
              <span className="absolute -left-2 top-1 h-4 w-4 rounded-full bg-primary" />
              <div className="flex items-center gap-2"><span className="font-semibold">v{r.v}</span><span className="text-xs text-muted-foreground">{r.date}</span></div>
              <ul className="mt-2 space-y-1 text-sm text-muted-foreground list-disc ml-4">{r.items.map((i) => <li key={i}>{i}</li>)}</ul>
            </div>
          ))}
        </div>
      </section>
    </main>
  );
}
