/**
 * What Cortex says to your customer.
 *
 * DELIBERATELY PURE — no database, no model call, no imports. The wording is
 * the riskiest surface in the product, so it is generated by code that can be
 * read in one sitting and tested exhaustively, rather than by a language model
 * whose output nobody sees until it has already been sent.
 *
 * WHY NOT LET THE AI WRITE IT.
 *
 * A model asked to "write a firm payment reminder" will, often enough to
 * matter, reach for leverage it does not have: legal action, credit reporting,
 * interest that was never agreed, a deadline nobody set. Those sentences are
 * sent in the OWNER'S NAME to a real business relationship, and in India an
 * unfounded threat of proceedings is not a small thing.
 *
 * The templates below are therefore fixed. The model is used elsewhere in the
 * product for analysis, where a wrong sentence costs nothing; here, the value
 * is in the timing and the tracking, not in the prose.
 *
 * WHAT THE LADDER DOES AND DOES NOT DO.
 *
 * Three attempts, escalating in DIRECTNESS only:
 *
 *   1. a nudge that assumes it was simply missed — which is usually true
 *   2. a clearer ask with the specifics restated
 *   3. a final note that asks for a date, and says the owner will follow up
 *      personally
 *
 * What never appears at any level: legal threats, mention of courts or notices,
 * interest or penalties that were not on the invoice, credit-bureau language,
 * or anything implying consequences the seller has not actually decided on.
 * Escalation is a matter of tone, never of invented leverage.
 */

export type Tone = "polite" | "neutral" | "firm";
export type Channel = "email" | "whatsapp";

export type DraftInput = {
  party: string;
  invoiceNo: string | null;
  amount: number;
  dueDate: string | null;
  daysPastDue: number;
  attempt: number;          // 1-based
  tone: Tone;
  businessName: string;
  signature?: string | null;
  paymentNote?: string | null;
  channel: Channel;
};

export type Draft = { subject: string | null; body: string };

const rupee = (n: number) =>
  "₹" + Math.round(n).toLocaleString("en-IN");

const prettyDate = (iso: string | null) => {
  if (!iso) return null;
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return null;
  return d.toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" });
};

/**
 * Phrases that must never appear in anything this module produces.
 *
 * Exported so the test can assert against the SAME list the code is written
 * against — a hardcoded copy in the test would drift, and the drift would be
 * silent until something unpleasant went out under a customer's name.
 */
export const FORBIDDEN = [
  "legal action", "legal notice", "lawyer", "advocate", "court", "sue", "suing",
  "police", "criminal", "recovery agent", "blacklist", "black list",
  "credit score", "credit bureau", "cibil", "defaulter",
  "penalty", "penal interest", "late fee", "interest will be charged",
  "final warning", "consequences", "we will be forced",
];

/** A short, human reference to the invoice. */
function reference(i: DraftInput): string {
  const bits: string[] = [rupee(i.amount)];
  if (i.invoiceNo) bits.push(`invoice ${i.invoiceNo}`);
  const due = prettyDate(i.dueDate);
  if (due) bits.push(`due ${due}`);
  return bits.join(", ");
}

function opening(i: DraftInput): string {
  const name = i.party.trim() || "there";
  return i.channel === "whatsapp" ? `Hi ${name},` : `Dear ${name},`;
}

function closing(i: DraftInput): string {
  const lines: string[] = [];
  if (i.paymentNote?.trim()) lines.push(i.paymentNote.trim());
  lines.push(i.signature?.trim() || i.businessName);
  return lines.join("\n");
}

/**
 * Build one reminder.
 *
 * `attempt` is clamped: a caller that loses count must not be able to produce a
 * harsher message than the ladder allows.
 */
export function draftReminder(input: DraftInput): Draft {
  const i = { ...input, attempt: Math.max(1, Math.min(3, input.attempt)) };
  const ref = reference(i);
  const late = i.daysPastDue > 0;

  let core: string;

  if (i.attempt === 1) {
    /*
      Assumes it was missed, because it usually was. Opening with an accusation
      costs a relationship for no gain — anyone who genuinely forgot pays after
      a nudge, and anyone who did not will not be moved by a harsher first line.
    */
    core = late
      ? `This is a gentle reminder about ${ref}, which is now ${i.daysPastDue} day${i.daysPastDue === 1 ? "" : "s"} past its due date. It may simply have been missed.`
      : `This is a gentle reminder about ${ref}.`;
  } else if (i.attempt === 2) {
    core = `Following up on ${ref}. It is now ${i.daysPastDue} day${i.daysPastDue === 1 ? "" : "s"} overdue and I do not think we have received it yet — could you let me know when it is likely to be released?`;
  } else {
    /*
      The last message asks for a DATE and says a person will follow up. That is
      the strongest honest position: it is specific, it is true, and it does not
      pretend to leverage that has not been decided on.
    */
    core = `I am writing once more about ${ref}, now ${i.daysPastDue} days overdue. Could you confirm a date by which it will be paid? If it is easier to discuss, I will call you this week.`;
  }

  /*
    Tone adjusts the surrounding words only. `firm` removes softeners; it never
    adds a threat, which is the whole point of separating tone from escalation.
  */
  const softener =
    i.tone === "polite" ? "\n\nIf it has already been paid, please ignore this and accept my apologies." :
    i.tone === "neutral" ? "\n\nIf it has already been paid, please let me know." :
    "";

  const bodyLines = [opening(i), "", core + softener, "", closing(i)];
  const body = bodyLines.join("\n").replace(/\n{3,}/g, "\n\n").trim();

  const subject = i.channel === "email"
    ? (i.attempt >= 3
        ? `Payment date for ${i.invoiceNo || rupee(i.amount)}`
        : `Reminder: ${i.invoiceNo ? `invoice ${i.invoiceNo}` : rupee(i.amount)} from ${i.businessName}`)
    : null;

  return { subject, body };
}

/**
 * Last line of defence before anything is stored or sent.
 *
 * The templates above cannot produce a forbidden phrase, but the SIGNATURE and
 * PAYMENT NOTE are free text the owner types — and an owner who writes "pay in
 * 3 days or we will take legal action" into their signature would otherwise
 * have it appended to every reminder Cortex sends. This is checked at the point
 * of drafting so it can never reach a recipient.
 */
export function containsForbidden(text: string): string | null {
  const t = String(text || "").toLowerCase();
  for (const phrase of FORBIDDEN) {
    if (t.includes(phrase)) return phrase;
  }
  return null;
}
