import { NextResponse } from "next/server";
import { generateFor } from "@/lib/ai/cortex";
import { getBusinessContext, getOrgProfile } from "@/lib/data";
import { sendEmail } from "@/lib/email";
import { ADMIN_EMAIL } from "@/lib/config";
import { mdToHtml } from "@/lib/utils";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function POST(req: Request) {
  try {
    const body = await req.json().catch(() => ({}));
    const context = await getBusinessContext();
    const brief = await generateFor("brief", "", context);
    let to = String(body?.to || "").trim();
    if (!to) { try { const p = await getOrgProfile(); to = (p as any)?.userEmail || ""; } catch {} }
    if (!to) to = ADMIN_EMAIL;
    const html = `<div style="font-family:system-ui,sans-serif;max-width:560px;margin:auto">
      <h2 style="color:#4f46e5">Your MNB Cortex daily brief</h2>
      <div style="font-size:14px;line-height:1.6;color:#111">${mdToHtml(brief)}</div>
      <p style="font-size:12px;color:#888;margin-top:24px">Generated by MNB Cortex — your AI COO.</p>
    </div>`;
    const res = await sendEmail(to, "Your MNB Cortex daily brief", html);
    return NextResponse.json({ ok: true, sent: res.sent, to, reason: res.reason, preview: brief });
  } catch (e: any) {
    return NextResponse.json({ ok: false, error: e?.message || "Failed" }, { status: 200 });
  }
}
