import { NextResponse } from "next/server";
import { generateFor } from "@/lib/ai/cortex";
import { getBusinessContext } from "@/lib/data";
import { sendEmail } from "@/lib/email";
import { mdToHtml } from "@/lib/utils";
import { chargeForMode, refundForMode } from "@/lib/credits";
import { creditDenial, requireWorkspace } from "@/lib/api-guard";
import { isSuperAdmin } from "@/lib/superadmin";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 60;

/**
 * Emails the owner their daily brief.
 *
 * The recipient is NOT taken from the request body for ordinary users — it is
 * always the signed-in user's own address. Accepting an arbitrary `to` made this
 * an open relay: anyone could have generated content on our AI key and sent it
 * from our Resend domain to any address, which is both a cost and a
 * deliverability/reputation risk. Only a platform super-admin may override it.
 */
export async function POST(req: Request) {
  const auth = await requireWorkspace();
  if (!auth.ok) return NextResponse.json(auth.body, { status: auth.status });

  const gate = await chargeForMode("brief");
  if (!gate.ok) {
    const d = creditDenial(gate, "Emailing your daily brief");
    return NextResponse.json(d.body, { status: d.status });
  }

  try {
    const body = await req.json().catch(() => ({} as any));

    // Recipient: the signed-in user, unless a super-admin explicitly targets someone.
    let to = auth.email;
    const requested = String(body?.to || "").trim();
    if (requested && requested.toLowerCase() !== to.toLowerCase()) {
      if (await isSuperAdmin()) to = requested;
      // else: silently ignore the override and send to the account owner.
    }
    if (!to) {
      if (gate.enforced) await refundForMode("brief");
      return NextResponse.json({ ok: false, error: "Your account has no email address on file." }, { status: 200 });
    }

    const context = await getBusinessContext();
    const brief = await generateFor("brief", "", context);
    if (!brief) {
      if (gate.enforced) await refundForMode("brief");
      return NextResponse.json({ ok: false, error: "Could not generate the brief — please try again." }, { status: 200 });
    }

    const html = `<div style="font-family:system-ui,sans-serif;max-width:560px;margin:auto">
      <h2 style="color:#4f46e5">Your MNB Cortex daily brief</h2>
      <div style="font-size:14px;line-height:1.6;color:#111">${mdToHtml(brief)}</div>
      <p style="font-size:12px;color:#888;margin-top:24px">Generated by MNB Cortex — your AI COO.</p>
    </div>`;
    const res = await sendEmail(to, "Your MNB Cortex daily brief", html);
    return NextResponse.json({ ok: true, sent: res.sent, to, reason: res.reason, preview: brief, charged: gate.enforced ? gate.cost : 0, balance: gate.balance });
  } catch (e: any) {
    if (gate.enforced) await refundForMode("brief");
    return NextResponse.json({ ok: false, error: e?.message || "Failed" }, { status: 200 });
  }
}
