#!/usr/bin/env node
/**
 * Turn a Cortex backup (.json.gz from /api/admin/backup) into reviewable SQL.
 *
 *   node scripts/restore.mjs cortex-backup-2026-08-26-05-12-33.json.gz > restore.sql
 *   node scripts/restore.mjs backup.json.gz --only=customers,invoices > partial.sql
 *   node scripts/restore.mjs backup.json.gz --check          # inspect, emit nothing
 *
 * WHY IT PRINTS SQL INSTEAD OF WRITING TO THE DATABASE
 *
 * A restore happens on the worst day of the quarter, usually at speed, usually
 * by someone frightened. A tool that connects to a live database and starts
 * writing is the wrong shape for that moment: there is no pause to read, no
 * diff, and a mistyped target destroys the one copy you had left. Emitting a
 * file means you can read it, grep it, restore one table, and hand it to
 * someone else to check before anything is written.
 *
 * It also means this script has no database driver and no credentials — it
 * cannot destroy anything by itself.
 *
 * WHAT IT DELIBERATELY WILL NOT DO
 *
 *  - It will not emit anything for a backup whose manifest says complete:false,
 *    unless you pass --force. Restoring a knowingly-partial backup over live
 *    data is how you turn one bad day into an unrecoverable one.
 *  - It does not DROP or TRUNCATE. Ever. Restoring INTO a populated table is a
 *    decision, so the emitted SQL uses ON CONFLICT DO NOTHING and tells you
 *    what to do if you actually want a replacement.
 *  - It does not restore api_keys.key or webhook_endpoints.secret, which are
 *    redacted in the backup by design. Those must be reissued.
 */

import { readFileSync } from "node:fs";
import { gunzipSync } from "node:zlib";

const args = process.argv.slice(2);
const file = args.find((a) => !a.startsWith("--"));
const force = args.includes("--force");
const checkOnly = args.includes("--check");
const only = (args.find((a) => a.startsWith("--only=")) || "").replace("--only=", "")
  .split(",").map((s) => s.trim()).filter(Boolean);

// Everything human-facing goes to stderr so `> restore.sql` stays pure SQL.
const say = (...m) => console.error(...m);

if (!file) {
  say("usage: node scripts/restore.mjs <backup.json.gz> [--only=t1,t2] [--check] [--force]");
  process.exit(2);
}

let payload;
try {
  payload = JSON.parse(gunzipSync(readFileSync(file)).toString("utf8"));
} catch (e) {
  say(`Could not read ${file}: ${e.message}`);
  process.exit(1);
}

const { manifest, data } = payload;
if (!manifest || !data) {
  say("That file does not look like a Cortex backup (no manifest/data).");
  process.exit(1);
}

say(`Backup taken:  ${manifest.takenAt}`);
say(`Project:       ${manifest.project}`);
say(`Rows:          ${Number(manifest.totalRows || 0).toLocaleString()}`);
say(`Complete:      ${manifest.complete}`);
for (const n of manifest.notes || []) say(`  ! ${n}`);
say("");

if (!manifest.complete && !force) {
  say("REFUSING: this backup reports itself INCOMPLETE.");
  say("Restoring a partial backup over live data can destroy rows the backup was missing.");
  say("Read the notes above. If you have decided it is safe, re-run with --force.");
  process.exit(1);
}
if (!manifest.complete && force) {
  say("PROCEEDING ON AN INCOMPLETE BACKUP because --force was given. Rows may be missing.");
  say("");
}

/** Postgres literal. Everything becomes text/JSON and is cast by the column type. */
function lit(v) {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") return Number.isFinite(v) ? String(v) : "NULL";
  if (typeof v === "boolean") return v ? "TRUE" : "FALSE";
  const s = typeof v === "object" ? JSON.stringify(v) : String(v);
  return `'${s.replace(/'/g, "''")}'`;
}

// Restore order matters: a child row whose parent does not exist yet fails on
// the foreign key. BACKUP_TABLES is already ordered parents-first, and the
// backup preserves that ordering, so we simply follow it.
const tables = Object.keys(data).filter((t) => !only.length || only.includes(t));

let statements = 0;
let rowsOut = 0;
const out = [];

out.push("-- Generated by scripts/restore.mjs — REVIEW BEFORE RUNNING.");
out.push(`-- Source backup: ${file}`);
out.push(`-- Taken at:      ${manifest.takenAt}`);
out.push(`-- Complete:      ${manifest.complete}`);
out.push("--");
out.push("-- Wrapped in a transaction: either the whole restore lands or none of it does.");
out.push("-- Inserts use ON CONFLICT DO NOTHING, so existing rows are left alone. If you");
out.push("-- intend to REPLACE a table, delete from it explicitly first, in your own");
out.push("-- statement, having thought about it.");
out.push("--");
out.push("-- NOT restored: database schema, auth.users, storage objects, and the redacted");
out.push("-- columns below. Create the schema first or every statement here will fail.");
for (const [t, cols] of Object.entries(manifest.redacted || {})) {
  out.push(`--   redacted: ${t}.${cols.join(", ")}  (reissue these after restoring)`);
}
out.push("");
out.push("BEGIN;");
out.push("");

for (const table of tables) {
  const rows = data[table] || [];
  if (!rows.length) { out.push(`-- ${table}: 0 rows`); continue; }

  const cols = [...new Set(rows.flatMap((r) => Object.keys(r)))];
  out.push(`-- ${table}: ${rows.length} rows`);

  // Batched so a single statement never becomes unreadably large — and so a
  // failure tells you roughly where it happened.
  const BATCH = 200;
  for (let i = 0; i < rows.length; i += BATCH) {
    const slice = rows.slice(i, i + BATCH);
    const values = slice
      .map((r) => `  (${cols.map((c) => lit(r[c])).join(", ")})`)
      .join(",\n");
    out.push(
      `INSERT INTO ${JSON.stringify(table).replace(/"/g, '"')} (${cols.map((c) => `"${c}"`).join(", ")}) VALUES\n${values}\nON CONFLICT DO NOTHING;`,
    );
    statements++;
  }
  rowsOut += rows.length;
  out.push("");
}

out.push("COMMIT;");
out.push("");

say(`Tables:     ${tables.length}`);
say(`Rows:       ${rowsOut.toLocaleString()}`);
say(`Statements: ${statements}`);

if (checkOnly) {
  say("\n--check given: no SQL written.");
  process.exit(0);
}

process.stdout.write(out.join("\n"));
