/*
  THE COLUMN THAT DECIDES WHO PAYS WAS THE ONE COLUMN NOBODY GUARDED.

  ============================================================================
  THE HOLE
  ============================================================================

  src/lib/credit-pool.ts opens by naming this attack, in its own words:

      "If a workspace could nominate its own payer, the cheapest possible
       exploit in the product would be: sign up, point `practice_org_id` at a
       large paying firm, and spend their month. So the link is one-directional
       and privileged:
         - The FIRM claims a client. A client can never attach itself to a firm.
         - The column lives on the CLIENT row but only the firm can write it."

  src/lib/credits.ts repeats it at the point of use: "It can only have been
  written by cortex_practice_claim()."

  Neither sentence was true. Three facts, each verified in this repo:

    1. 2026_tenancy.sql grants row UPDATE on organizations to anyone with
       user_org_rank(id) >= 4, and every signup becomes owner (rank 5) of the
       workspace it creates. So an owner may PATCH their own row.

    2. 2026_zzzd_practice_pool.sql adds practice_org_id to that row. There is
       no column GRANT anywhere on organizations — by design; see the long
       note in 2026_org_billing_guard.sql about why column grants fail in the
       wrong direction.

    3. cortex_guard_org_billing() — the trigger that is therefore the ONLY
       column-level control — does not list practice_org_id. It could not:
       the guard was written before the column existed, and migrations are
       applied in order.

  So:

      PATCH /rest/v1/organizations?id=eq.<my-own-org>
      { "practice_org_id": "<a Practice firm's uuid>" }

  succeeds with nothing but the public anon key and the attacker's own
  session. cortex_practice_claim — which proves owner/admin of the firm AND
  membership of the client — is simply never involved.

  WHAT IT COSTS. resolvePayer() re-checks that the named firm is on
  practice/enterprise and active, and then charges it:

      chargeOrgForMode -> payerOrgId = firm -> charge_credits(p_org: firm)

  Every AI action in the attacker's workspace is debited from the victim
  firm's pooled allowance, Veo video included at the ~₹77/clip this repo
  costs it at. src/lib/billing.ts resolves the same link for entitlement, so
  the attacker's unpaid workspace is also unlocked, and getCreditState reports
  the VICTIM's balance and allowance on the attacker's own screen — a cross-
  tenant disclosure on top of the theft.

  The firm's uuid is not secret to the people most likely to use it: a current
  or former pooled client reads practice_org_id off its own row through the
  normal SELECT policy, and cortex_practice_release only nulls the column —
  nothing stopped the released client writing it straight back.

  ============================================================================
  WHY THE EXISTING GUARD'S OWN TEST DID NOT CATCH IT
  ============================================================================

  2026_org_billing_guard.sql predicted this failure exactly:

      "A trigger ... names the columns that are DANGEROUS, and anything new is
       allowed by default. Adding a column can now cause a security gap
       instead of an outage — so the accompanying test asserts this list still
       covers every billing column the application reads."

  That was the right design and the right instinct. The test, though, compared
  the migration against a HAND-WRITTEN list of seven column names, and built
  its PGlite fixture from a hand-written CREATE TABLE carrying the same
  columns. Both copies encoded the 2026 assumption. A column added in 2026_zzzd
  was invisible to both, so the coverage assertion passed by having nothing to
  say. scripts/test-billing-guard.mjs now derives the column set from the
  migrations themselves and requires every column to be either protected or
  explicitly classified as safe for a workspace owner to edit.

  ============================================================================
  THIS MIGRATION
  ============================================================================

  Replaces cortex_guard_org_billing() with two more names in the protected
  array. Nothing else changes: same signature, same SECURITY INVOKER (see the
  original file for why definer rights silently disable it), same trigger.

  · practice_org_id — decides whose credits pay and whose plan entitles.
  · referral_code   — src/lib/referrals.ts resolves a code string back to an
                      org id to attribute a reward. It is generated by a
                      trigger and no legitimate UI writes it, so a user
                      editing their own is either pointless or an attempt to
                      intercept somebody else's attribution.

  Idempotent. Re-running costs nothing. The trigger itself is untouched and
  keeps pointing at this function.
*/

create or replace function cortex_guard_org_billing()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  protected constant text[] := array[
    'credits',              -- the balance itself
    'credits_allowance',    -- -1 here disables metering entirely
    'credits_reset_at',     -- moving this backwards re-triggers the monthly top-up
    'plan',
    'subscription_status',
    'subscription_ends_at',
    'subscription_cycle',
    'subscription_ref',
    'trial_ends_at',
    'autorenew_status',
    'autorenew_next',
    /*
      Added after the fact, which is the whole point of the note above: these
      two were reachable for as long as they have existed.
    */
    'practice_org_id',      -- whose credits pay, and whose plan entitles
    'referral_code'         -- the key another org's reward is attributed by
  ];
  col       text;
  old_json  jsonb := to_jsonb(OLD);
  new_json  jsonb := to_jsonb(NEW);
begin
  -- service_role, postgres, supabase_admin and the migration runner pass freely.
  if current_user not in ('authenticated', 'anon') then
    return NEW;
  end if;

  foreach col in array protected loop
    /*
      `is distinct from` is kept from the original, and it is worth being
      precise about what it is and is not doing here, because the first
      version of this comment claimed something false.

      It said: practice_org_id is normally NULL, so plain <> would let the
      NULL-to-value attack through. That is true of a RAW column comparison —
      `NULL <> 'zz'` is NULL, not true — but NOT of this one. Measured on
      Postgres: `to_jsonb(OLD) -> 'practice_org_id'` on a NULL column yields
      JSON `null`, which is a VALUE, so `<>` against a real uuid already
      returns true. Through the jsonb round-trip the two operators agree.

      So the jsonb conversion is what actually makes the NULL case safe, and
      `is distinct from` is correct-by-construction rather than load-bearing.
      It stays because it costs nothing and because the day someone rewrites
      this to compare OLD.col with NEW.col directly, it is the version that
      still works.
    */
    if (old_json -> col) is distinct from (new_json -> col) then
      /*
        Message and errcode copied verbatim from 2026_org_billing_guard.sql.
        This migration exists to widen the list, not to change behaviour —
        and the message is asserted on by scripts/test-billing-guard.mjs.
      */
      raise exception
        'column "%" on organizations is billing-controlled and cannot be changed by role "%"',
        col, current_user
        using errcode = '42501';   -- insufficient_privilege
    end if;
  end loop;

  return NEW;
end $$;

/*
  The trigger already exists and already points at this function, so replacing
  the body is enough. Created here too, guarded, for a database built from
  scratch in a different order.
*/
do $$
begin
  if not exists (
    select 1 from pg_trigger
     where tgname = 'cortex_org_billing_guard'
       and tgrelid = 'public.organizations'::regclass
  ) then
    create trigger cortex_org_billing_guard
      before update on organizations
      for each row execute function cortex_guard_org_billing();
  end if;
end $$;

/*
  ============================================================================
  AND THE CAP THAT WAS ENFORCED ON A NUMBER THE CALLER SENT
  ============================================================================

  cortex_practice_claim() is granted to `authenticated` — correctly, it
  authenticates the caller itself. It takes the client cap as an ARGUMENT:

      create function cortex_practice_claim(p_firm uuid, p_client uuid,
                                            p_limit int default 25)
      ...
      if p_limit >= 0 then ... if v_count >= p_limit then
           return 'client-limit-reached';

  under a comment reading "The cap the pricing page advertises, enforced where
  it cannot be bypassed." src/lib/actions.ts does resolve the right number
  server-side, but the browser can call the RPC directly with p_limit = -1 and
  skip the branch entirely. A ₹29,999/mo Practice account advertised as "up to
  25 client workspaces" funds an unlimited number.

  The action's own comment two functions up gets the principle exactly right
  about a different argument: "p_firm is taken from the SESSION's current
  workspace, never from the request — otherwise the firm id would be an
  attacker-controlled input and the whole guard would rest on a value they
  chose." p_limit is that value.

  Not cross-tenant: the caller must still be owner/admin of the firm and a
  member of each client, so this is a subscriber widening their own plan, not
  a stranger taking something. Entitlement leakage, not theft — which is why
  it rides along with the P0 above rather than getting its own file.

  THE FIX. Look the limit up from the firm's plan, inside the function. The
  parameter stays for signature compatibility (the grant, and the call in
  actions.ts, both name the three-argument form) but can now only make the cap
  STRICTER, never looser: `least()` of what the caller asked for and what the
  plan actually allows. A caller may be conservative; a caller may not help
  themselves.

  PRACTICE_CLIENTS in src/lib/config.ts is the source of truth for the
  numbers; scripts/test-credit-pool.mjs pins the two together.
*/
create or replace function cortex_practice_claim(p_firm uuid, p_client uuid, p_limit int default 25)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user       uuid := auth.uid();
  v_rank       text;
  v_plan       text;
  v_count      int;
  v_plan_limit int;
  v_limit      int;
begin
  if v_user is null then return 'not-signed-in'; end if;
  if p_firm is null or p_client is null then return 'missing-argument'; end if;
  if p_firm = p_client then return 'cannot-claim-self'; end if;

  select role into v_rank from memberships
   where org_id = p_firm and user_id = v_user limit 1;
  if v_rank is null then return 'not-a-member-of-firm'; end if;
  if v_rank not in ('owner', 'admin') then return 'insufficient-rank'; end if;

  if not exists (select 1 from memberships where org_id = p_client and user_id = v_user) then
    return 'not-a-member-of-client';
  end if;

  select lower(coalesce(plan, '')) into v_plan from organizations where id = p_firm;
  if v_plan is null then return 'firm-not-found'; end if;
  if v_plan not in ('practice', 'enterprise') then return 'firm-plan-has-no-pooling'; end if;

  /*
    THE CAP, DERIVED HERE. Mirrors PRACTICE_CLIENTS in src/lib/config.ts:
    practice 25, enterprise -1 (negotiated by hand). Any other pooling plan
    added later and not listed here gets 0 rather than unlimited — a new plan
    should fail to claim and be noticed, not silently pool without a ceiling.
  */
  v_plan_limit := case v_plan
                    when 'practice'   then 25
                    when 'enterprise' then -1
                    else 0
                  end;

  /*
    The caller may tighten, never loosen. -1 from the plan means unlimited, so
    it must not win a `least()` against a positive request; handle it first.
  */
  if v_plan_limit < 0 then
    v_limit := case when p_limit is null or p_limit < 0 then -1 else p_limit end;
  else
    v_limit := case when p_limit is null or p_limit < 0 then v_plan_limit
                    else least(p_limit, v_plan_limit) end;
  end if;

  if v_limit >= 0 then
    select count(*) into v_count from organizations
     where practice_org_id = p_firm and id <> p_client;
    if v_count >= v_limit then return 'client-limit-reached'; end if;
  end if;

  update organizations set practice_org_id = p_firm where id = p_client;
  return 'ok';
end $$;

/*
  WHY THE NEW TRIGGER DOES NOT BREAK THIS.

  cortex_guard_org_billing() now refuses a write to practice_org_id from
  `authenticated` or `anon`. The UPDATE above happens inside a SECURITY
  DEFINER function, so current_user is the function's owner (postgres), the
  guard's first test passes, and the legitimate claim path is untouched. Same
  for cortex_practice_release(), which is also definer. This is asserted, not
  assumed: scripts/test-credit-pool.mjs runs both against real Postgres.
*/

/* ---------------------------------------------------------------- verify ---
   All four must be true. Each reads the function body Postgres actually
   holds, so only the replacements above can satisfy them.
   -------------------------------------------------------------------------- */
select
  (select prosrc like '%practice_org_id%' from pg_proc
    where proname = 'cortex_guard_org_billing' limit 1)  as practice_link_protected,
  (select prosrc like '%referral_code%' from pg_proc
    where proname = 'cortex_guard_org_billing' limit 1)  as referral_code_protected,
  (select prosrc like '%v_plan_limit%' from pg_proc
    where proname = 'cortex_practice_claim' limit 1)     as client_cap_server_side,
  cortex_has_billing_guard()                             as trigger_installed;
